# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created: Fri Apr 10 19:48:18 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(616, 455)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.centerLayout = QtGui.QHBoxLayout()
        self.centerLayout.setObjectName(_fromUtf8("centerLayout"))
        self.gridLayout.addLayout(self.centerLayout, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 616, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTask = QtGui.QMenu(self.menuBar)
        self.menuTask.setObjectName(_fromUtf8("menuTask"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAnalyze = QtGui.QAction(MainWindow)
        self.actionAnalyze.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/analyze")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyze.setIcon(icon1)
        self.actionAnalyze.setObjectName(_fromUtf8("actionAnalyze"))
        self.actionAddROI = QtGui.QAction(MainWindow)
        self.actionAddROI.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddROI.setIcon(icon2)
        self.actionAddROI.setObjectName(_fromUtf8("actionAddROI"))
        self.actionOCR = QtGui.QAction(MainWindow)
        self.actionOCR.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ocr")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOCR.setIcon(icon3)
        self.actionOCR.setObjectName(_fromUtf8("actionOCR"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setEnabled(True)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/about")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setEnabled(True)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionRestroe = QtGui.QAction(MainWindow)
        self.actionRestroe.setEnabled(False)
        self.actionRestroe.setObjectName(_fromUtf8("actionRestroe"))
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon5)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAnalyze)
        self.toolBar.addAction(self.actionAddROI)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOCR)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionLog)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRestroe)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTask.addAction(self.actionAnalyze)
        self.menuTask.addAction(self.actionAddROI)
        self.menuTask.addSeparator()
        self.menuTask.addAction(self.actionOCR)
        self.menuTask.addAction(self.actionClear)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTask.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "zoomBar", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuTask.setTitle(_translate("MainWindow", "Task", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open", None))
        self.actionAnalyze.setText(_translate("MainWindow", "Analyze", None))
        self.actionAnalyze.setToolTip(_translate("MainWindow", "Analyze", None))
        self.actionAddROI.setText(_translate("MainWindow", "AddROI", None))
        self.actionOCR.setText(_translate("MainWindow", "OCR", None))
        self.actionOCR.setToolTip(_translate("MainWindow", "OCR", None))
        self.actionHelp.setText(_translate("MainWindow", "&Help", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionExit.setText(_translate("MainWindow", "&Exit", None))
        self.actionLog.setText(_translate("MainWindow", "&Log", None))
        self.actionRestroe.setText(_translate("MainWindow", "&Restroe", None))
        self.actionClear.setText(_translate("MainWindow", "&Clear", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear", None))

import resources_rc
