# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created: Wed Apr 15 20:45:46 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainGUI(object):
    def setupUi(self, MainGUI):
        MainGUI.setObjectName(_fromUtf8("MainGUI"))
        MainGUI.setWindowModality(QtCore.Qt.ApplicationModal)
        MainGUI.resize(616, 455)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/app")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainGUI.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.centerLayout = QtGui.QHBoxLayout()
        self.centerLayout.setObjectName(_fromUtf8("centerLayout"))
        self.gridLayout.addLayout(self.centerLayout, 0, 0, 1, 1)
        MainGUI.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainGUI)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainGUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 616, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuTask = QtGui.QMenu(self.menuBar)
        self.menuTask.setObjectName(_fromUtf8("menuTask"))
        MainGUI.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainGUI)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainGUI.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(MainGUI)
        self.actionOpen.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAnalyze = QtGui.QAction(MainGUI)
        self.actionAnalyze.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/analyze")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyze.setIcon(icon2)
        self.actionAnalyze.setObjectName(_fromUtf8("actionAnalyze"))
        self.actionAddROI = QtGui.QAction(MainGUI)
        self.actionAddROI.setCheckable(True)
        self.actionAddROI.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/add")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddROI.setIcon(icon3)
        self.actionAddROI.setObjectName(_fromUtf8("actionAddROI"))
        self.actionOCR = QtGui.QAction(MainGUI)
        self.actionOCR.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ocr")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOCR.setIcon(icon4)
        self.actionOCR.setObjectName(_fromUtf8("actionOCR"))
        self.actionHelp = QtGui.QAction(MainGUI)
        self.actionHelp.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/help")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainGUI)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/about")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSave = QtGui.QAction(MainGUI)
        self.actionSave.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon7)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionExit = QtGui.QAction(MainGUI)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon8)
        self.actionExit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLog = QtGui.QAction(MainGUI)
        self.actionLog.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/log")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLog.setIcon(icon9)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.actionClear = QtGui.QAction(MainGUI)
        self.actionClear.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clear")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon10)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionRestore = QtGui.QAction(MainGUI)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/restore")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRestore.setIcon(icon11)
        self.actionRestore.setObjectName(_fromUtf8("actionRestore"))
        self.actionShow = QtGui.QAction(MainGUI)
        self.actionShow.setEnabled(False)
        self.actionShow.setIcon(icon)
        self.actionShow.setObjectName(_fromUtf8("actionShow"))
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionRestore)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAnalyze)
        self.toolBar.addAction(self.actionAddROI)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOCR)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLog)
        self.toolBar.addAction(self.actionShow)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionLog)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRestore)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTask.addAction(self.actionAnalyze)
        self.menuTask.addAction(self.actionAddROI)
        self.menuTask.addSeparator()
        self.menuTask.addAction(self.actionOCR)
        self.menuTask.addAction(self.actionClear)
        self.menuTask.addSeparator()
        self.menuTask.addAction(self.actionShow)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTask.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainGUI)
        QtCore.QMetaObject.connectSlotsByName(MainGUI)

    def retranslateUi(self, MainGUI):
        MainGUI.setWindowTitle(_translate("MainGUI", "Michelangelo", None))
        self.toolBar.setWindowTitle(_translate("MainGUI", "zoomBar", None))
        self.menuAbout.setTitle(_translate("MainGUI", "Help", None))
        self.menuFile.setTitle(_translate("MainGUI", "File", None))
        self.menuTask.setTitle(_translate("MainGUI", "Task", None))
        self.actionOpen.setText(_translate("MainGUI", "Open...", None))
        self.actionOpen.setToolTip(_translate("MainGUI", "Open", None))
        self.actionOpen.setStatusTip(_translate("MainGUI", "Open image files", None))
        self.actionAnalyze.setText(_translate("MainGUI", "Analyze", None))
        self.actionAnalyze.setToolTip(_translate("MainGUI", "Analyze", None))
        self.actionAnalyze.setStatusTip(_translate("MainGUI", "Find the text areas", None))
        self.actionAddROI.setText(_translate("MainGUI", "AddROI", None))
        self.actionAddROI.setStatusTip(_translate("MainGUI", "Add the text area", None))
        self.actionOCR.setText(_translate("MainGUI", "OCR", None))
        self.actionOCR.setToolTip(_translate("MainGUI", "OCR", None))
        self.actionOCR.setStatusTip(_translate("MainGUI", "Start OCR", None))
        self.actionHelp.setText(_translate("MainGUI", "&Help", None))
        self.actionHelp.setStatusTip(_translate("MainGUI", "Get the online help", None))
        self.actionAbout.setText(_translate("MainGUI", "&About", None))
        self.actionAbout.setStatusTip(_translate("MainGUI", "About this application", None))
        self.actionSave.setText(_translate("MainGUI", "&Save", None))
        self.actionSave.setStatusTip(_translate("MainGUI", "Save the results", None))
        self.actionExit.setText(_translate("MainGUI", "&Exit", None))
        self.actionExit.setStatusTip(_translate("MainGUI", "Exit the application", None))
        self.actionLog.setText(_translate("MainGUI", "&Log", None))
        self.actionLog.setStatusTip(_translate("MainGUI", "Check the logs", None))
        self.actionClear.setText(_translate("MainGUI", "&Clear", None))
        self.actionClear.setToolTip(_translate("MainGUI", "Clear", None))
        self.actionClear.setStatusTip(_translate("MainGUI", "Clear and reset", None))
        self.actionRestore.setText(_translate("MainGUI", "&Restore", None))
        self.actionRestore.setStatusTip(_translate("MainGUI", "Restore a json file", None))
        self.actionShow.setText(_translate("MainGUI", "&Show", None))
        self.actionShow.setToolTip(_translate("MainGUI", "Show something", None))

import resources_rc
